package services

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/all-things-book-club/internal/crypto"
	"github.com/all-things-book-club/internal/db"
)

type RecurringRuleService struct {
	db *pgxpool.Pool
}

// ErrRecurringRuleExists is returned when a chapter already has an active recurring rule.
var ErrRecurringRuleExists = errors.New("chapter already has an active recurring rule")

func NewRecurringRuleService(db *pgxpool.Pool) *RecurringRuleService {
	return &RecurringRuleService{db: db}
}

// GetDB returns the database pool for use in route handlers
func (s *RecurringRuleService) GetDB() *pgxpool.Pool {
	return s.db
}

// RecurringRuleInput is the data the client sends when scheduling a recurring meeting series.
type RecurringRuleInput struct {
	ChapterID             string     `json:"chapterId"`
	Frequency             string     `json:"frequency"`
	Interval              int        `json:"interval"`
	StartDate             time.Time  `json:"startDate"`
	EndDate               *time.Time `json:"endDate"`
	Duration              int        `json:"duration"`
	LocationEncryptedBlob []byte     `json:"locationEncryptedBlob"`
	LocationNonce         []byte     `json:"locationNonce"`
}

// Create inserts a new recurring rule and its first meeting occurrence (scheduled at
// the rule's start date). Later occurrences are generated by the recurring meeting
// generator job, which copies the location blob forward from the previous occurrence.
func (s *RecurringRuleService) Create(ctx context.Context, input RecurringRuleInput, userID string) (*Meeting, error) {
	ok, err := db.IsMember(ctx, s.db, input.ChapterID, userID)
	if err != nil {
		return nil, fmt.Errorf("RecurringRuleService.Create: %w", err)
	}
	if !ok {
		return nil, db.ErrNotMember
	}

	var hasActiveRule bool
	err = s.db.QueryRow(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM recurring_rules
			WHERE chapter_id = $1 AND (end_date IS NULL OR end_date > now())
		)
	`, input.ChapterID).Scan(&hasActiveRule)
	if err != nil {
		return nil, fmt.Errorf("RecurringRuleService.Create: check existing rule: %w", err)
	}
	if hasActiveRule {
		return nil, ErrRecurringRuleExists
	}

	ruleID, err := crypto.GenerateID()
	if err != nil {
		return nil, fmt.Errorf("RecurringRuleService.Create: generate rule ID: %w", err)
	}

	tx, err := s.db.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("RecurringRuleService.Create: begin transaction: %w", err)
	}
	defer tx.Rollback(ctx) // no-op if tx.Commit() is called below

	_, err = tx.Exec(ctx, `
		INSERT INTO recurring_rules (id, chapter_id, frequency, interval, start_date, end_date, duration, created_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, now())
	`, ruleID, input.ChapterID, input.Frequency, input.Interval, input.StartDate, input.EndDate, input.Duration)
	if err != nil {
		return nil, fmt.Errorf("RecurringRuleService.Create: insert rule: %w", err)
	}

	meetingID, err := crypto.GenerateID()
	if err != nil {
		return nil, fmt.Errorf("RecurringRuleService.Create: generate meeting ID: %w", err)
	}

	var m Meeting
	err = tx.QueryRow(ctx, `
		INSERT INTO meetings (id, chapter_id, duration, scheduled_at, recurring_group_id,
			created_at, updated_at, status, location_encrypted_blob, location_nonce)
		VALUES ($1, $2, $3, $4, $5, now(), now(), 'SCHEDULED', $6, $7)
		RETURNING id, chapter_id, duration, scheduled_at, status, recurring_group_id
	`, meetingID, input.ChapterID, input.Duration, input.StartDate, ruleID,
		input.LocationEncryptedBlob, input.LocationNonce).
		Scan(&m.ID, &m.ChapterID, &m.Duration, &m.ScheduledAt, &m.Status, &m.RecurringGroupId)
	if err != nil {
		return nil, fmt.Errorf("RecurringRuleService.Create: insert first meeting: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("RecurringRuleService.Create: commit: %w", err)
	}

	m.LocationEncryptedBlob = input.LocationEncryptedBlob
	m.LocationNonce = input.LocationNonce
	return &m, nil
}

// RecurringRule is the client-facing representation of a recurring_rules row.
type RecurringRule struct {
	ID        string     `json:"id"`
	ChapterID string     `json:"chapterId"`
	Frequency string     `json:"frequency"`
	Interval  int        `json:"interval"`
	StartDate time.Time  `json:"startDate"`
	EndDate   *time.Time `json:"endDate"`
	Duration  int        `json:"duration"`
}

// GetByID fetches a recurring rule, verifying the caller belongs to its chapter.
func (s *RecurringRuleService) GetByID(ctx context.Context, ruleID string, userID string) (*RecurringRule, error) {
	var rule RecurringRule
	err := s.db.QueryRow(ctx, `
		SELECT r.id, r.chapter_id, r.frequency, r.interval, r.start_date, r.end_date, r.duration
		FROM recurring_rules r
		JOIN chapter_members cm ON cm.chapter_id = r.chapter_id AND cm.user_id = $2
		WHERE r.id = $1
	`, ruleID, userID).
		Scan(&rule.ID, &rule.ChapterID, &rule.Frequency, &rule.Interval, &rule.StartDate, &rule.EndDate, &rule.Duration)
	if err != nil {
		return nil, fmt.Errorf("RecurringRuleService.GetByID: %w", err)
	}
	return &rule, nil
}

// UpdateFrequency changes how often a recurring rule repeats.
func (s *RecurringRuleService) UpdateFrequency(ctx context.Context, ruleID string, frequency string) error {
	_, err := s.db.Exec(ctx, `
		UPDATE recurring_rules SET frequency = $1 WHERE id = $2
	`, frequency, ruleID)
	if err != nil {
		return fmt.Errorf("RecurringRuleService.UpdateFrequency: %w", err)
	}
	return nil
}

// UpdateInterval changes the "every N units" interval of a recurring rule.
func (s *RecurringRuleService) UpdateInterval(ctx context.Context, ruleID string, interval int) error {
	_, err := s.db.Exec(ctx, `
		UPDATE recurring_rules SET interval = $1 WHERE id = $2
	`, interval, ruleID)
	if err != nil {
		return fmt.Errorf("RecurringRuleService.UpdateInterval: %w", err)
	}
	return nil
}

// UpdateDuration changes how long each generated occurrence lasts.
func (s *RecurringRuleService) UpdateDuration(ctx context.Context, ruleID string, duration int) error {
	_, err := s.db.Exec(ctx, `
		UPDATE recurring_rules SET duration = $1 WHERE id = $2
	`, duration, ruleID)
	if err != nil {
		return fmt.Errorf("RecurringRuleService.UpdateDuration: %w", err)
	}
	return nil
}

// UpdateEndDate changes (or clears, if endDate is nil) when a recurring rule stops generating occurrences.
func (s *RecurringRuleService) UpdateEndDate(ctx context.Context, ruleID string, endDate *time.Time) error {
	_, err := s.db.Exec(ctx, `
		UPDATE recurring_rules SET end_date = $1 WHERE id = $2
	`, endDate, ruleID)
	if err != nil {
		return fmt.Errorf("RecurringRuleService.UpdateEndDate: %w", err)
	}
	return nil
}

// dueRecurringRule holds the columns needed to compute and insert the next occurrence.
type dueRecurringRule struct {
	ID        string
	ChapterID string
	Frequency string
	Interval  int
	Duration  int
	EndDate   *time.Time
}

// nextOccurrence advances lastScheduled by the rule's frequency/interval.
func nextOccurrence(lastScheduled time.Time, frequency string, interval int) time.Time {
	switch frequency {
	case "MINUTES":
		return lastScheduled.Add(time.Duration(interval) * time.Minute)
	case "DAILY":
		return lastScheduled.AddDate(0, 0, interval)
	case "WEEKLY":
		return lastScheduled.AddDate(0, 0, 7*interval)
	case "MONTHLY":
		return lastScheduled.AddDate(0, interval, 0)
	case "MONTHLY_WEEKDAY":
		return nextMonthlyWeekday(lastScheduled, interval)
	default:
		return lastScheduled.AddDate(0, 0, 7*interval)
	}
}

// nextMonthlyWeekday returns the same Nth occurrence of lastScheduled's weekday
// (e.g. the 1st Thursday), `interval` months later. If that occurrence doesn't
// exist in the target month (e.g. a 5th occurrence), it falls back to the last
// one that does.
func nextMonthlyWeekday(lastScheduled time.Time, interval int) time.Time {
	weekday := lastScheduled.Weekday()
	occurrence := (lastScheduled.Day()-1)/7 + 1

	totalMonths := int(lastScheduled.Month()) - 1 + interval
	year := lastScheduled.Year() + totalMonths/12
	month := time.Month(totalMonths%12 + 1)

	first := time.Date(year, month, 1, lastScheduled.Hour(), lastScheduled.Minute(),
		lastScheduled.Second(), lastScheduled.Nanosecond(), lastScheduled.Location())
	day := 1 + (int(weekday-first.Weekday()+7) % 7) + (occurrence-1)*7

	for {
		candidate := time.Date(year, month, day, lastScheduled.Hour(), lastScheduled.Minute(),
			lastScheduled.Second(), lastScheduled.Nanosecond(), lastScheduled.Location())
		if candidate.Month() == month {
			return candidate
		}
		day -= 7 // requested occurrence doesn't exist this month, use the last one
	}
}

// GenerateUpcomingOccurrences creates the next meeting for every recurring rule whose
// most recent meeting's computed next occurrence is due, copying the location blob
// forward (discussion notes intentionally start empty for the new occurrence).
func (s *RecurringRuleService) GenerateUpcomingOccurrences(ctx context.Context) error {
	rows, err := s.db.Query(ctx, `
		SELECT r.id, r.chapter_id, r.frequency, r.interval, r.duration, r.end_date,
			m.scheduled_at, m.location_encrypted_blob, m.location_nonce
		FROM recurring_rules r
		JOIN meetings m ON m.recurring_group_id = r.id
		WHERE m.scheduled_at = (
			SELECT MAX(scheduled_at) FROM meetings WHERE recurring_group_id = r.id
		)
	`)
	if err != nil {
		return fmt.Errorf("RecurringRuleService.GenerateUpcomingOccurrences: query due rules: %w", err)
	}
	defer rows.Close()

	type candidate struct {
		rule                  dueRecurringRule
		lastScheduled         time.Time
		locationEncryptedBlob []byte
		locationNonce         []byte
	}
	var candidates []candidate
	for rows.Next() {
		var c candidate
		if err := rows.Scan(&c.rule.ID, &c.rule.ChapterID, &c.rule.Frequency, &c.rule.Interval,
			&c.rule.Duration, &c.rule.EndDate, &c.lastScheduled, &c.locationEncryptedBlob, &c.locationNonce); err != nil {
			return fmt.Errorf("RecurringRuleService.GenerateUpcomingOccurrences: scan: %w", err)
		}
		candidates = append(candidates, c)
	}

	for _, c := range candidates {
		next := nextOccurrence(c.lastScheduled, c.rule.Frequency, c.rule.Interval)
		if next.After(time.Now().AddDate(0, 0, 14)) {
			continue // only generate occurrences within a 2-week lookahead window
		}
		if c.rule.EndDate != nil && next.After(*c.rule.EndDate) {
			continue // recurrence has ended
		}

		meetingID, err := crypto.GenerateID()
		if err != nil {
			return fmt.Errorf("RecurringRuleService.GenerateUpcomingOccurrences: generate meeting ID: %w", err)
		}

		_, err = s.db.Exec(ctx, `
			INSERT INTO meetings (id, chapter_id, scheduled_at, duration, status, recurring_group_id,
				location_encrypted_blob, location_nonce, created_at, updated_at)
			VALUES ($1, $2, $3, $4, 'SCHEDULED', $5, $6, $7, now(), now())
		`, meetingID, c.rule.ChapterID, next, c.rule.Duration, c.rule.ID, c.locationEncryptedBlob, c.locationNonce)
		if err != nil {
			return fmt.Errorf("RecurringRuleService.GenerateUpcomingOccurrences: insert meeting for rule %s: %w", c.rule.ID, err)
		}
	}

	return nil
}
